//! TypeScript bindings export (host-only; `cargo run --features typegen --bin export-types`).

use std::fs;
use std::io;
use std::path::PathBuf;

use ts_rs::TS;

use crate::effect::EffectCommand;
use crate::event::AppEvent;
use crate::frame::SpiralFrame;
use engine_kernel::{PatchSegment, ViewModelPatch};
use crate::protocol::{WorkerInput, WorkerOutput};
use crate::state::{Metric, Zoom};
use crate::view_mode::ViewMode;
use crate::view_model::{CityOption, ViewModel};

const GENERATED_HEADER: &str = "// This file was generated by `npm run generate:types`. Do not edit.\n\n";

pub fn export_types() -> io::Result<()> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/generated");
    fs::create_dir_all(&dir)?;
    let path = dir.join("engine-types.ts");

    let mut out = String::from(GENERATED_HEADER);
    append_decl::<PatchSegment>(&mut out);
    append_decl::<ViewModelPatch>(&mut out);
    append_decl::<Metric>(&mut out);
    append_decl::<Zoom>(&mut out);
    append_decl::<ViewMode>(&mut out);
    append_decl::<CityOption>(&mut out);
    append_decl::<SpiralFrame>(&mut out);
    append_decl::<AppEvent>(&mut out);
    append_decl::<EffectCommand>(&mut out);
    append_decl::<ViewModel>(&mut out);
    append_decl::<WorkerInput>(&mut out);
    append_decl::<WorkerOutput>(&mut out);

    fs::write(path, out)
}

fn append_decl<T: TS + 'static>(out: &mut String) {
    let decl = T::decl();
    if let Some(rest) = decl.strip_prefix("type ") {
        out.push_str("export type ");
        out.push_str(rest);
    } else {
        out.push_str(&decl);
    }
    out.push_str("\n\n");
}
